name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Shell Check
      run: |
        apt update
        apt install shellcheck
        shellcheck psx2chd.sh || exit
