name: macOS

on: [push]

jobs:
  lint:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Shell Check
      run: |
        brew update
        brew install shellcheck
        shellcheck psx2chd.sh
